### ISSUE TITLE
仅仅好奇的问问，现在还用UIWebview吗？

### ISSUE THREAD

**Issue by weiminghuaa** [yuantiku/YTKWebView-iOS#3]
新项目我想应该会用WKWebView了，老项目肯定仍然很大用UIWebview，但也逐渐迁移了吧，我记得微信2年前就换WKWebView了，现在还开源UIWebView的封装，会不会有点过时？

ps: 仅仅好奇问问，没有任何不尊重开源精神的意思，仅从实用性问以下

**Comment by perfectworks** [comment]
WKWebView 在 iOS 11 以下只能通过私有 API 来实现 JS 同步调用。
我们期望在未来的某个时间，iOS 11+ 的版本覆盖率达到一定程度后，切换 WKWebView
