### ISSUE TITLE
提升加载速度的原理在哪里？

### ISSUE THREAD

**Issue by loveway** [yuantiku/YTKWebView-iOS#6]

**Comment by perfectworks** [comment]
资源是通过 YTKResourceCache 预先加载的，所以不需要再发网络请求去获取资源
另外通过 Bridge LifeCycle 使得 WebView 知道首屏是否渲染完成，避免了渲染前的白屏，实现秒开效果
现在 YTKWebApp 还在 WIP 阶段，后续会补整体的 Demo，谢谢关注
